### ISSUE TITLE
RGB light stays blue and cannot be turned off

### ISSUE THREAD

**Issue by CFDaniel1893** [corus87/tuxedo-xmg-keyboard-backlight-control-script#1]
Hello everybody,

I am using a XMG Core 15 with Ubuntu 20.04. and the Tuxedo Control Center.
Earlier I was able to turn on/off the RGB light with Fn+Space.
After installation the RGB light stays blue and I cannot turn it off or change the mode or color of the light.

I just tested the script but I get following error:
tee: /sys/devices/platform/tuxedo_keyboard/uw_kbd_bl_color/color_string: No such file or directory
tee: /sys/devices/platform/tuxedo_keyboard/uw_kbd_bl_color/brightness: No such file or directory

I installed tuxedo keyboard from here 
https://www.tuxedocomputers.com/de/Infos/Hilfe-Support/Hilfe-fuer-mein-Geraet/XMG-FUSION-Serie/XMG-FUSION-15/Intel-QC7-Ubuntu-20-04-Installation.tuxedo

I am not sure in which file I exactly have to add my device name.

Do you recommend to uninstall the tuxedo_keyboard version I installed previously and install the one from here with my device name added in src/uniwill_keyboard.h?
https://github.com/tuxedocomputers/tuxedo-keyboard

**Comment by corus87** [comment]
The files will only show up if you own a tuxedo devices. 
But since the [tuxedo kernel module](https://github.com/tuxedocomputers/tuxedo-keyboard) is open source, and the core 15 got the same hardware, you can modify the source-code and add your model to it. 

Either you download the source by yourself and add your model [to this line](https://github.com/corus87/tuxedo-keyboard/blob/fbf0b2ed79af0a11805e53a2fb7d2bc89b83a04f/src/uniwill_keyboard.h#L458) or you use [my branch](https://github.com/corus87/tuxedo-keyboard) where I already added the core 15 and compile it according to the readme. 

Here are some copy and paste commands for my branch, what should install it:

```
git clone https://github.com/corus87/tuxedo-keyboard
cd tuxedo-keyboard
make clean && make
sudo make dkmsremove (Since you already got tuxedo-keyboard installed, remove the dkms first)
sudo make dkmsinstall
sudo rmmod tuxedo_keyboard (remove the old module)
sudo modprobe tuxedo_keyboard 
```
You may also need to install some depenciens like:
```
sudo apt-get install build-essential dkms git
```

But before using my branch, check the output of `cat /sys/class/dmi/id/board_name` if it match `GK5NxxO M20` otherwise you have to add it as mentioned.

**Comment by CFDaniel1893** [comment]
I checked my board_name and have the same as you. But still I downloaded the source by myself and added the necessary line. I then tried to follow your commands (thanks a lot!) but now I get the following error when executing sudo rmmod tuxedo_keyboard:
rmmod: ERROR: Module tuxedo_keyboard is in use by: tuxedo_io clevo_wmi

Do you know how to bypass this error?

**Comment by corus87** [comment]
try this ` sudo rmmod tuxedo_io && sudo rmmod clevo_wmo && sudo rmmod tuxedo_keyboard` 
but a reboot should also work

**Comment by CFDaniel1893** [comment]
Nice, I had to restart but after restarting I could change the color and brightness! Thank you very much!
Is it also possible to switch to another mode, for example waving or cycling? Just out of curiosity.

**Comment by corus87** [comment]
You welcome. 
No it's not possible to use the modes provided by the tuxedo-keyboard module, those only work on other Tuxedo models but not yet on Polaris or XMG Core.

But it is possible, maybe they add it in near future, or someone else writes a small program.
